name: Safe Mode CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-safe-mode:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck

      - name: Run ShellCheck
        run: shellcheck safeguard.sh

      - name: Run Safe Mode Tests
        run: |
          chmod +x test_safemode.sh
          ./test_safemode.sh
